"""empty message

Revision ID: 50c1e3876cef
Revises: bab74a9774cb
Create Date: 2021-02-05 23:36:04.327862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c1e3876cef'
down_revision = 'bab74a9774cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weblogdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IP', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('URL', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('http', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weblogdb')
    # ### end Alembic commands ###
