"""empty message

Revision ID: bab74a9774cb
Revises: 7ebc0deeb7e1
Create Date: 2021-02-05 16:18:03.337810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bab74a9774cb'
down_revision = '7ebc0deeb7e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weblogdb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('IP', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('URL', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('http', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('column_not_exist_in_db', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('column_not_exist_in_db', name='logs_pkey')
    )
    op.drop_table('weblogdb')
    # ### end Alembic commands ###
