FROM python:3.6-slim
COPY . /app
WORKDIR /app
RUN pip install --upgrade pip
RUN pip install setuptools==46.1.3

RUN set -ex \
  && apt-get -y update

RUN pip install -r requirements.txt
ENTRYPOINT [ "python" ]
CMD [ "consumer.py" ]
